version: 2.1
 
orbs:
  android: circleci/android@2.1.2
  snyk: snyk/snyk@1.4.0
 
jobs:
  build:
    executor: 
        name: android/android-machine
        tag: 2022.12.1
    steps:
        - checkout
        - restore_cache:
            key: android-orb-v1-
        - run:
            name: Chmod permissions
            command: sudo chmod +x ./gradlew
        - run:
            name: Download Dependencies
            command: ./gradlew androidDependencies
        - save_cache:
            key: 'android-orb-v1-{{ epoch }}'
            paths:
                - ~/.android/build-cache
                - ~/.android/cache
        - run:
            name: Run Build
            command: ./gradlew build
        - store_artifacts: 
            path: app/build/reports
            destination: reports
        - run:
            name: Run Tests
            command: ./gradlew lint test
        - store_test_results:
            path: app/build/test-results
        - store_artifacts:  
            path: app/build/outputs/apk/debug/
            destination: artifact-file
        - snyk/scan:
            project: '${CatzApp}/${circle-project-setup}-app'
            severity-threshold: high
            token-variable: SNYK_TOKEN